services:
  pgdb:
    image: postgres
    container_name: pgdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: myschooldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
      - "8001:8001"

  django:
    build: .
    container_name: django
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py create_default_users &&
      python manage.py create_superuser &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    environment:
      DEBUG: '1'
      DJANGO_ALLOWED_HOSTS: 'localhost 127.0.0.1'
      CELERY_BROKER: 'redis://redis:6379/0'
      CELERY_BACKEND: 'redis://redis:6379/0'
      DJANGO_SUPERUSER_USERNAME: 'admin'
      DJANGO_SUPERUSER_EMAIL: 'admin@example.com'
      DJANGO_SUPERUSER_PASSWORD: 'admin'
    depends_on:
      - pgdb
      - redis

  celery:
    build: .
    command: celery -A core worker -l INFO
    volumes:
      - .:/usr/src/app
    depends_on:
      - django
      - redis

volumes:
  pgdata:
