version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: myschooldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_db:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack
    container_name: redis_db
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_db:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis-listener:
      image: alpine:latest
      container_name: redis_listener
      restart: always
      depends_on:
        - redis
      volumes:
        - logs:/logs
      command: sh -c "while true; do redis-cli -h redis -p 6379 --scan --pattern '*' >> /logs/logs.txt; sleep 5; done"


volumes:
  postgres_db:
    driver: local
  redis_db:
    driver: local
  logs:
    driver: local
